version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - brain-agriculture-network

  backend:
    image: brain-agriculture-backend:latest
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    networks:
      - brain-agriculture-network

networks:
  brain-agriculture-network:
    driver: bridge
